### ISSUE TITLE
[FEATURE] Improve the title

### ISSUE THREAD

**Issue by ana-os-mo** [salitomeyo/desarrollo-web#4]
**Describe any problem this feature request is related to**
The title is too boring and doesn't make the visitor feel part of the journey.

**Describe the solution you'd like**
I would change it for something more eye-catching

**Describe alternatives you've considered**
A good alternative could be:
# "Welcome stranger to Neverland"

**Comment by salitomeyo** [comment]
This was resolved in 7c7f594fbe61ef5c031ca8d3824f912f91ed84c8
